blank_issues_enabled: false
contact_links:
  - name: Community Support
    url: https://github.com/open-telemetry/community
    about: Please ask and answer questions here.
  - name: OpenTelemetry Slack
    url: https://cloud-native.slack.com/archives/CJFCJHG4Q
    about: For live discussion with the community and contributors